-- Japan Trip Companion — user accounts, step 6: the flight belongs to a trip.
--
-- `FLIGHT` was a module constant in server/src/lib/flight.ts holding one
-- specific booking, and `getTripBundle` attached it to whichever trip was
-- being read. With one trip that was just where the data lived. With open
-- registration it means a stranger's first trip to anywhere arrives carrying
-- somebody else's booking reference and ticket times.
--
-- jsonb rather than a `trip_flights` table: legs are read as a block and never
-- edited individually, so a table would buy a join and two store methods for
-- nothing. If legs ever become separately editable, that is the moment to
-- split them out.
--
-- This migration adds the column and nothing else. It originally carried an
-- `update` that seeded one trip's real booking reference and ticket times —
-- a live credential checked into a public repo, where it stayed readable long
-- after the row itself had been written. A booking reference is trip data: it
-- belongs in the row, entered through the app, never in source control.
-- Migrations from here on ship schema, not anyone's reservations.
--
-- Run after 0016.

alter table trips add column if not exists flight jsonb;
